### ISSUE TITLE
Remove infodiversity header

### ISSUE THREAD

**Issue by glciampaglia** [CSDL-USF/Rockwell#153]
Per title. It may give the game away.

**Comment by 1449Antonio** [comment]
Before removing it though, do you want any sort of replacement, or should we remove the banner as well and simply have the very top of the app start with the box that says "Feed # of 5 ..."? 

Furthermore, if we plan to remove the header because it gives it away, should we also edit the launch screen and change the name of the app for the Twitter Authorization screen. Both these screens also include "infodiversity" in them.

**Comment by glciampaglia** [comment]
We discussed it. We will not remove the navbar, since telemetry code depends on it being there. We will rename infodiversity to Rockwell.
