### ISSUE TITLE
MTurk pilot survey - bugs and things still left to implement

### ISSUE THREAD

**Issue by saumyabhadani95** [CSDL-USF/Rockwell#177]
The following small things are still left to do in the Qualtrics survey before deploying it to Mechanical Turk:
- [x] @saumyabhadani95: Display mobile-friendly screenshots in attention check
- [x] @saumyabhadani95: Handle the request timeout error for the eligibility API (check `error` field in returned JSON, if true, display `errorMessage`)
- [x] ~~@aychen5: End of survey may be too abrupt - maybe change the message?~~
- [x] @saumyabhadani95: Detect pop-up blocker and display message with instructions for disabling blocker. 
- [x] @aychen5: in informed consent, the yes/no question should be mandatory. Right now it is possible to move to the next screen without entering any answer. 
- [x] @aychen5: same for screen 4 (_How frequently do you share political news on social media sites such as Facebook, Instagram, or Twitter?_); it is possible to move past the screen without answering. (It does show a modal dialog asking if you want to continue without answering, but it would be simpler to just make this mandatory as well.)
- [x] @saumyabhadani95: need to refresh the tweet screenshots ~~with latest rockwell interface~~ with tweets from twitter.com.
- [x] @saumyabhadani95: text of tweet screenshots is not legible (especially on mobile but also on desktop).
- [x] @saumyabhadani95: some screenshots (ex. trump, school buses) include the attention check question.
- [x] @aychen5: allow users to review feed on second attempt.
- [x] @aychen5: randomize order of posts in pre-attention check
- [x] @aychen5: update text of twitter auth invite (see doc with track changes [here](https://docs.google.com/document/d/1Hw-zY3uGZAsqg7nUvwlrrA54w-Ibl1pE/edit?usp=sharing&ouid=106394434287530909612&rtpof=true&sd=true))

**Comment by glciampaglia** [comment]
Regarding the pop-up blocker, the following behavior was observed for Firefox:
  - On iPhone, Firefox works if user disables pop-ups from Firefox settings (not the iOS settings);
  - On Android, pop-up blocker asks whether to allow pop-up, but then after completing login, qualtrics does not advance to confirmation screen;
  - On Linux desktop, firefox works only the second time and/or if one adds exception for pop-up blocking.
 
We have added code to detect that the pop-up was blocked and display a reminder about disabling it. Since it is not possible to disable the pop-up blocker in Firefox on Android. In the reminder we invite the user to use a different browser. Note that this is not a problem on iPhone since it is possible to disable the blocker from the Firefox app settings (not the iOS settings).
