### ISSUE TITLE
Construct ranked feed from home timeline tweets

### ISSUE THREAD

**Issue by saumyabhadani95** [CSDL-USF/Rockwell#47]
We need to rank the tweets obtained from the home timeline (which is chronologically ordered) into the feed, making sure to include both tweets with links to Newsguard domains, and other tweets (either with non-NG links or without any link). 

Depending on the treatment (chronological vs recommender system), the ranking should take into account the predicted ratings of the user from the recommendation system. 

One issue is how to mix the NG tweets and the non-NG tweets. The following document describes the problem and possible solutions: [Feed Construction document](https://docs.google.com/document/d/11NCQ1WyN_gSLgVZtgEBrcBSp30nRg3Qd6-PcrtgpKj4/edit?usp=sharing).

**UPDATE**: we have decided to use Option 1, the simple random mixing. We will rank all the tweets once, and split them in pages after the ranking.

**Comment by glciampaglia** [comment]
To discuss with Annie:
- What is the proportion of NG tweets to non-NG tweets we want to use

**Comment by glciampaglia** [comment]
We have discussed this issue with the rest of the team. We have decided that we will use a 50% proportion (on average 5 NG tweets per screen). However, we will do one single ranking upfront and then shuffle in the non-NG tweets, and only then we will break up the list into groups of 10. So pages will have different proportions of NG to non-NG tweets.

**Comment by glciampaglia** [comment]
@thomasbiv will talk with @RobertAndion to go through steps to determine when tweet is newsguard (see eligibility code), and will create Python function that does same thing to be called within `/getfeed`.

**Comment by glciampaglia** [comment]
The splitting of newsguard and non-newsguard tweets is almost complete. First, we need to add to the fronted an attribute that tells whether a tweet is newsguard or not. Then we will test this without scores. Next we will need to discuss how to use the scores for ranking and the exact procedure for splitting the pages (see [above comment](https://github.com/CSDL-USF/Rockwell/issues/47#issuecomment-912062670))

**Comment by glciampaglia** [comment]
Here is the exact procedure for splitting the pages:
1. Count the number of NewsGuard tweets NT and of other tweet OT;
2. Let PT = NT / (OT + NT);
3. If PT > 0.5, let PT = 0.5 (we do not want more than 50% NewsGuard tweets in the feed;
4. Rank all NewsGuard tweets and select the top 50 * PT tweets (rounded) and create a stack;
5. Select the 50 * (1 - PT) other tweets and create a stack;
6. Create an empty list of size 50;
7. For each position i from 1 to 50:
   7.1. With probability PT pop the NewsGuard stack and assign the tweet in position i; otherwise pop the "Other" stack and assign the tweet in position i in the list;
8. Split the list in 5 screens and record the rank and screen of each tweet in the DB for later use by the frontend.
